stages:
  - stage: A
    jobs:
    - job: A1Job 
      steps:
       - task: Bash@3
         displayName: "compiling code"
         inputs:
          targetType: 'inline'
          script: 'javac HelloWorld.java'
        
       - task: Bash@3
         displayName: "running"
         inputs:
          targetType: 'inline'
          script: 'java HelloWorld'
